//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRafic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRafic()
        {
            this.Rabotnikis = new HashSet<Rabotniki>();
        }
    
        public int NomerGrafika { get; set; }
        public System.TimeSpan Nacalo { get; set; }
        public System.TimeSpan Konec { get; set; }
        public int VidGrafica { get; set; }
        public Nullable<int> Tip_Graf { get; set; }
    
        public virtual TipGrafik TipGrafik { get; set; }
        public virtual Vid_Grafika Vid_Grafika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rabotniki> Rabotnikis { get; set; }
    }
}
