//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public static Entities1 _con;
        public Entities1()
            : base("name=Entities1")
        {
        }
        public static Entities1 Go()
        {
            if (_con==null)
            {
                _con = new Entities1();
            }
            return _con;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BesRab> BesRabs { get; set; }
        public virtual DbSet<GRafic> GRafics { get; set; }
        public virtual DbSet<Komapania> Komapanias { get; set; }
        public virtual DbSet<Obrasavanie> Obrasavanies { get; set; }
        public virtual DbSet<ObrasovanieProfessi> ObrasovanieProfessis { get; set; }
        public virtual DbSet<Professia> Professias { get; set; }
        public virtual DbSet<ProfImeut> ProfImeuts { get; set; }
        public virtual DbSet<Rabotniki> Rabotnikis { get; set; }
        public virtual DbSet<RolRabotnicov> RolRabotnicovs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipGrafik> TipGrafiks { get; set; }
        public virtual DbSet<TipORganisacii> TipORganisaciis { get; set; }
        public virtual DbSet<TipSanatosti> TipSanatostis { get; set; }
        public virtual DbSet<UcrejdenieObr> UcrejdenieObrs { get; set; }
        public virtual DbSet<Vacansja> Vacansjas { get; set; }
        public virtual DbSet<Vid_Grafika> Vid_Grafika { get; set; }
    }
}
