//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObrasovanieProfessi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObrasovanieProfessi()
        {
            this.ProfImeuts = new HashSet<ProfImeut>();
        }
    
        public int NomerProfObras { get; set; }
        public int NomerUcrejdenieOrganisacia { get; set; }
        public int NomerProfessia { get; set; }
    
        public virtual Professia Professia { get; set; }
        public virtual UcrejdenieObr UcrejdenieObr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfImeut> ProfImeuts { get; set; }
    }
}
