//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfImeut
    {
        public int NomerProfImenut { get; set; }
        public int NomerFIO { get; set; }
        public int NomerProfObras { get; set; }
    
        public virtual BesRab BesRab { get; set; }
        public virtual ObrasovanieProfessi ObrasovanieProfessi { get; set; }
    }
}
