//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabotniki
    {
        public string Login { get; set; }
        public string Parol { get; set; }
        public string FIO { get; set; }
        public string NOmerTelefona { get; set; }
        public byte[] Fotografija { get; set; }
        public System.DateTime DateRojdenia { get; set; }
        public string Pocta { get; set; }
        public int RolRabotnikaNomre { get; set; }
        public int NomerGrafika { get; set; }
        public int Oplata { get; set; }
    
        public virtual GRafic GRafic { get; set; }
        public virtual RolRabotnicov RolRabotnicov { get; set; }
    }
}
