//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcrejdenieObr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UcrejdenieObr()
        {
            this.BesRabs = new HashSet<BesRab>();
            this.ObrasovanieProfessis = new HashSet<ObrasovanieProfessi>();
        }
    
        public int NomerUcrejdenieOrganisacia { get; set; }
        public string CratNaim { get; set; }
        public string PolnNaim { get; set; }
        public string Adres { get; set; }
        public int NomerObrasovanie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BesRab> BesRabs { get; set; }
        public virtual Obrasavanie Obrasavanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObrasovanieProfessi> ObrasovanieProfessis { get; set; }
    }
}
