//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacansja
    {
        public int NomerVacansija { get; set; }
        public int NomerProfessia { get; set; }
        public int NomerRabocajaNedela { get; set; }
        public decimal Oplata { get; set; }
        public int NomerComapanii { get; set; }
    
        public virtual Komapania Komapania { get; set; }
        public virtual Professia Professia { get; set; }
        public virtual TipSanatosti TipSanatosti { get; set; }
    }
}
